# fly.toml file generated for precrypt on 2022-02-07T15:24:35-05:00

app = "rwtp-graph-node"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image="graphprotocol/graph-node:latest"

[env]
  postgres_host="subgraph-pg.internal"
  postgres_port=5432
  postgres_user="app"
  postgres_db="rinkeby"
  ipfs="rwtp-ipfs.internal:5001"
  ethereum="rinkeby:https://rinkeby.infura.io/v3/ea07de956656482f818e0af2d688726d"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[services]]
  internal_port = 8020
  protocol = "tcp"
  
  [[services.ports]]
    port = "8020"

[[services]]
  internal_port = 8030
  protocol = "tcp"
  
  [[services.ports]]
    port = "8030"
